CREATE TABLE user_accounts (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                               email VARCHAR(255) NOT NULL UNIQUE,
                               password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE user_profiles (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               created_at TIMESTAMP(6) WITHOUT TIME ZONE,
                               email VARCHAR(255) NOT NULL UNIQUE,
                               first_name VARCHAR(255) NOT NULL,
                               height_cm DOUBLE PRECISION,
                               last_name VARCHAR(255) NOT NULL,
                               weight_kg DOUBLE PRECISION,
                               user_account_id BIGINT UNIQUE,
                               CONSTRAINT fk_user_profiles_user_account
                                   FOREIGN KEY (user_account_id)
                                       REFERENCES user_accounts(id)
);

CREATE TABLE foods (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       brand VARCHAR(255),
                       calories DOUBLE PRECISION NOT NULL,
                       carbohydrate_grams DOUBLE PRECISION NOT NULL,
                       created_at TIMESTAMP(6) WITHOUT TIME ZONE,
                       fat_grams DOUBLE PRECISION NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       protein_grams DOUBLE PRECISION NOT NULL,
                       serving_size_grams DOUBLE PRECISION NOT NULL
);

CREATE TABLE nutrition_goals (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 calorie_target INTEGER NOT NULL,
                                 carbohydrate_target_grams INTEGER NOT NULL,
                                 created_at TIMESTAMP(6) WITHOUT TIME ZONE,
                                 fat_target_grams INTEGER NOT NULL,
                                 protein_target_grams INTEGER NOT NULL,
                                 user_profile_id BIGINT NOT NULL UNIQUE,
                                 CONSTRAINT fk_nutrition_goals_user_profile
                                     FOREIGN KEY (user_profile_id)
                                         REFERENCES user_profiles(id)
);

CREATE TABLE food_logs (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           created_at TIMESTAMP(6) WITHOUT TIME ZONE,
                           eaten_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                           meal_type VARCHAR(255) NOT NULL,
                           quantity_grams DOUBLE PRECISION NOT NULL,
                           food_id BIGINT NOT NULL,
                           user_profile_id BIGINT NOT NULL,

                           CONSTRAINT food_logs_meal_type_check
                               CHECK (
                                   meal_type IN (
                                                 'BREAKFAST',
                                                 'LUNCH',
                                                 'DINNER',
                                                 'SNACK'
                                       )
                                   ),

                           CONSTRAINT fk_food_logs_food
                               FOREIGN KEY (food_id)
                                   REFERENCES foods(id),

                           CONSTRAINT fk_food_logs_user_profile
                               FOREIGN KEY (user_profile_id)
                                   REFERENCES user_profiles(id)
);